### ISSUE TITLE
Bitcoin Private transactions invalid.

### ISSUE THREAD

**Issue by ianpurton** [onchain/onchain-gem#1]
Transactions created with onchain rejected by Bitcoin Private network.

i.e. 

      tx_hex, inputs_to_sign = OnChain::Transaction.create_single_address_transaction(
        'b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm', 
        'b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9', 482699, 
        17000, 'b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9', 300, :bitcoin_private)

Generates after signing

010000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006b4830450221008726bb261d8e4fb75c2286c076e38ee0a713dd4496e062dae05b61e2c20e671802207d0ec20ed87df0c02105d9d9b6f4039ec4c82822b325fcf2bbc534675d7d8dc9412103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac00000000

Gives the error

An error occured:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element). Code:-26

Example test case https://github.com/onchain/onchain-gem/blob/master/spec/lib/bitcoin_private_spec.rb#L9

**Steps to reproduce**

1. Create a BTCP address on https://paperwallet.btcprivate.org
2. Send it 0.005 BTCP
3. Check bitcoin_private_spec.rb#L9 so it represents your new address and UTXO
4. Set your private key as an ENV var. i.e. export private_key=L9....
5. Run the test case rspec spec/lib/bitcoin_private_spec.rb:9
6. Try to send the tranasction from https://explorer.btcprivate.org/tx/send

**Example output from Testcase**

Public Key we are using - b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm
Unsigned TX
010000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000001976a9148a1dde437f546b20222b4a4434c8b9dd4d8b05ba88acffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac00000000

Inputs before signing.
{"1DbJ2kfB4LEFiWCnBfQtip3qNYeCW4fPCT"=>{"hash"=>"c4692ac0360ec55b812f7c68a066f6fe9d3ba6d2c1e550885ebdb0f3be391640"}}

Inputs after signing.
{"1DbJ2kfB4LEFiWCnBfQtip3qNYeCW4fPCT"=>{"hash"=>"c4692ac0360ec55b812f7c68a066f6fe9d3ba6d2c1e550885ebdb0f3be391640", "sig"=>"3045022100fdc4ee897213141511dc4c9ae2babacc615a10d2fa15c7ca0547b149338b7358022047d2e539e8e05f3c9d1164565f0bd3cd0c45ed80b96259d1c9af0c601fca65e7"}}

Signed? true
Verified? true

Signed TX
010000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006b483045022100fdc4ee897213141511dc4c9ae2babacc615a10d2fa15c7ca0547b149338b7358022047d2e539e8e05f3c9d1164565f0bd3cd0c45ed80b96259d1c9af0c601fca65e7412103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac00000000

**Comment by pranav13100** [comment]
ok

**Comment by ianpurton** [comment]
I changed the call
 and got this TX and error

010000000175031c53cfc21e9ee3966380b9adc4d991a8224c04f3d297a2b26e045b2d83db000000006a4730440220718e975f19dec024b4bcd09fd3ecde5d6fee57afcc8908bd94bceb829fce8d0602205d428e60b954c072b19603ab42ab6ea6688a5a0b223c7f233933bbd192aebe35012103e131d6f9e9f83cfa18de2e89887cc4c829ab99c230bc884c22ddb6ffab19e121ffffffff028b5d0700000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac68420000000000001976a9143a48bfebcdc52c7b3831eab75a1955e58744c7e388ac00000000

An error occured:
16: mandatory-script-verify-flag-failed (Signature hash type missing or not understood). Code:-26

**Comment by pranav13100** [comment]
oh ok.. so thats not the problem .. that was correct before

**Comment by pranav13100** [comment]
tx_hex, inputs_to_sign = OnChain::Transaction.create_single_address_transaction(
    'b1H4VhwWAoVGMqnXM8oqsKK2WzpMGkbRamm', 
    'b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9', 482699, 
    17000, 'b19nP23vNEyWiyz6B9G5hFnt7w12RAPbsU9', 300, network = :bitcoin_private)

**Comment by ianpurton** [comment]
It's aleady set to :bitcoin_private. I tried that but still same result. The problem is at the protocol level not just trying different ways of calling the methods.

**Comment by pranav13100** [comment]
whats the output for ```.do_we_have_all_the_signatures(inputs_to_sign)``` ??

**Comment by ianpurton** [comment]
The output is true.

I think you would have to run your own test case it would be much quicker than asking me to run things for you.

**Comment by ianpurton** [comment]
Had a implement input hashing function specific to Bitcoin Private.
